### ISSUE TITLE
trouble pasting into deploy & run

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-vscode#13]
I have copied an address to the clipboard but it wont let me paste it into the AtAddress or to interact with a function.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/6050001/122630086-58951c80-d08f-11eb-8899-08da249ccd74.png">

I can type into the input box - just not paste.

**Comment by bunsenstraat** [comment]
fixed in the 0.0.9
