### ISSUE TITLE
Question regarding the scope of the project

### ISSUE THREAD

**Issue by Manas-Nanivadekar** [ethereum/remix-vscode#2]
Is this extension aiming to provide an entire remix like environment in vscode or just providing plugins? I'm working on creating remix like environment in vscode. It would be nice to know if creating remix like environment in vscode is planned.

**Comment by bunsenstraat** [comment]
There are plans to extend it yes. What are you working on? Let's talk on discord or gitter?

**Comment by bunsenstraat** [comment]
closing due to no issue, we're glad to see new projects!
