### ISSUE TITLE
Test vscode

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-vscode#7]
I have published a test version of the vscode extension which now includes run & deploy.
The run & deploy app has been extended with local node support.
The app is in the plugin list.
To compile open a sol file, shift-command-p search for compile, you can use solidity extension or remix.
Output of compilation and deployment is in the terminal.

The test version is here:
https://marketplace.visualstudio.com/items?itemName=bunsenstraat.ethereum-remix
! make sure to uninstall the normal remix extension otherwise there will be conflicts.

**Comment by yann300** [comment]
This works pretty well (I tried it with ganache) !

**Comment by phazejeff** [comment]
I have successfully compiled my contract, but it isn't showing up in the drop down menu for the contracts in the run & deploy app.

**Comment by bunsenstraat** [comment]
Can you describe the procedure? How did you compile it exactly? Or make a sreencapture if you can?
