### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Abhijnan-Bajpai** [ethereum/remix-vscode#9]
- Issue Type: `Performance`
- Extension Name: `ethereum-remix`
- Extension Version: `0.0.7`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

[RemixProject.ethereum-remix-unresponsive.cpuprofile.txt](https://github.com/ethereum/remix-vscode/files/6536837/RemixProject.ethereum-remix-unresponsive.cpuprofile.txt)

**Comment by bunsenstraat** [comment]
Are you running any plugins in the extension?

**Comment by bunsenstraat** [comment]
closing issue due to no more info. please update to 0.0.8, it's a lighter build.
